server.port=8080
server.address=0.0.0.0

# Swagger UI Customization
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=list
springdoc.swagger-ui.syntax-highlight.theme=monokai
# Cargar el CSS personalizado para el modo oscuro
springdoc.swagger-ui.custom-css=/custom-swagger.css
